name: kalshi_mobile_challenge
description: "Take Home Assignment."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  kiwi: ^5.0.1
  currency_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
    - assets/images/logos/

  fonts:
    - family: Rubik
      fonts:    
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
    - family: Work_Sans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Work_Sans/WorkSans-Light.ttf
          weight: 300    
        - asset: assets/fonts/Work_Sans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Work_Sans/WorkSans-Black.ttf
          weight: 900